#!/bin/bash
# Shebang: specifies that this is a bash script

newTsp() {
# Create the project directory
mkdir "$1"
cd "$1"

# Initialize git 
git init
touch README.md
touch .gitignore

# Add node_modules to .gitignore
echo "node_modules" > .gitignore
echo "dist" >> .gitignore

# Initialize NPM project
npm init -y

# Install TypeScript and ts-node
npm install --save-dev typescript ts-node

# Initialize TypeScript
npx tsc --init --moduleResolution node16 --module es2022  --target es2022 --outDir dest

# Create src/index.ts
mkdir src
touch src/index.ts
echo 'console.log("Hello World!");' > src/index.ts

# Create a .gitignore file
echo "
# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test
.env.production

# parcel-bundler cache (https://parceljs.org/)
.cache

# Next.js build output
.next

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and *not* Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/cache
.yarn/unplugged

# next.js
.next/

# nuxt.js
.nuxt/

# vuepress
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# sveltekit build output
.svelte-kit

# Astro
.astro

# Remix
.cache

# Vercel
.vercel

# Storybook build outputs
.out
storybook-static

# RedwoodJS
.redwood/types
.redwood/schema
api/dist/prisma

# Prisma
node_modules/.prisma

# Jest intermediate
.jest-cache

# Cache directory for @vue/cli-service

# Cache directory for vite

" > .gitignore

# Adds a script to easily start your project
npm set-script start "ts-node src/index.ts"

echo "
Project initialized successfully!
"
}
