import fs from 'fs';
import path from 'path';

/**
 * tsp-distill-to-js: Transforms a TS workspace package into a bundled JS distribution.
 * Part of the newTsp toolkit.
 * * Usage: node tsp_distill_to_js.js <target-path> <source-ts-package-name>
 */

const [,, targetPathRaw, tsPackageName] = process.argv;

if (!targetPathRaw || !tsPackageName) {
  console.error("❌ Usage: node tsp_distill_to_js.js <target-path> <ts-package-name>");
  process.exit(1);
}

const TARGET_DIR = path.resolve(process.cwd(), targetPathRaw);
const folderName = path.basename(TARGET_DIR);

// Generate a valid JS identifier for the global variable/barrel name
const camelCaseName = folderName
  .replace(/[-_]([a-z])/g, (g) => g[1].toUpperCase())
  .replace(/^[a-z]/, (g) => g.toUpperCase())
  .replace(/[^a-zA-Z0-9]/g, '');

function distill() {
  console.log(`📦 Distilling: [${tsPackageName}] (TS) -> [${folderName}] (JS Bundle)`);

  // 1. Create directory structure
  if (!fs.existsSync(path.join(TARGET_DIR, 'src'))) {
    fs.mkdirSync(path.join(TARGET_DIR, 'src'), { recursive: true });
  }

  // 2. Generate package.json
  const pkg = {
    name: folderName,
    version: "1.0.0",
    description: `Pre-bundled JavaScript distribution of ${tsPackageName}`,
    type: "module",
    main: "./dist/index.cjs",
    module: "./dist/index.js",
    browser: "./dist/index.global.js",
    types: "./dist/index.d.ts",
    exports: {
      ".": {
        types: "./dist/index.d.ts",
        import: "./dist/index.js",
        require: "./dist/index.cjs",
        script: "./dist/index.global.js"
      }
    },
    scripts: {
      "build": "tsup",
      "dev": "tsup --watch",
      "prepublishOnly": "npm run build"
    },
    dependencies: {
      [tsPackageName]: "*" 
    },
    devDependencies: {
      "tsup": "^8.5.1",
      "typescript": "^5.0.0",
      "@types/node": "^22.0.0"
    }
  };

  fs.writeFileSync(
    path.join(TARGET_DIR, 'package.json'), 
    JSON.stringify(pkg, null, 2)
  );

  // 3. Generate tsup.config.ts
  const tsupConfig = `import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['cjs', 'esm', 'iife'],
  globalName: '${camelCaseName}',
  dts: true,
  clean: true,
  target: 'es2015',
  minify: true,
  bundle: true,
  // This is the core 'distill' logic: bundle the TS package logic into the JS output
  noExternal: ['${tsPackageName}'], 
  sourcemap: true,
  splitting: false,
});`;

  fs.writeFileSync(path.join(TARGET_DIR, 'tsup.config.ts'), tsupConfig);

  // 4. Generate src/index.ts (The Bridge)
  const indexSource = `/**
 * Generated by tsp-distill-to-js
 * Symmetric wrapper for the ${tsPackageName} core engine.
 */
import * as Core from '${tsPackageName}';

// Re-export all named exports from the TS core
export * from '${tsPackageName}';

/**
 * Barrel Namespace
 * Provides dot-notation access, useful for IIFE/Global browser usage.
 */
export const ${camelCaseName} = {
  ...Core
} as const;
`;

  fs.writeFileSync(path.join(TARGET_DIR, 'src/index.ts'), indexSource);

  console.log(`\n✨ Distillation successful!`);
  console.log(`📍 Location: ${TARGET_DIR}`);
  console.log(`🏗️  Identifier: ${camelCaseName}`);
  console.log(`\nNext steps:`);
  console.log(`1. Run 'npm install' at the workspace root.`);
  console.log(`2. Run 'npm run build -w ${folderName}' to generate the JS bundles.`);
}

distill();
