newTsp_help() {
  echo ""
  echo "newTsp - TypeScript Project Initializer"
  echo ""
  echo "USAGE:"
  echo "  newTsp <project-name> [options]"
  echo ""
  echo "ARGUMENTS:"
  echo "  project-name             Name of the project to create (required)"
  echo ""
  echo "OPTIONS:"
  echo "  -h, --help               Display this help message"
  echo "  -n, --node               Initialize a Node.js backend project"
  echo "  --typezero               Initialize using TypeZero template"
  echo ""
  echo "PROJECT TYPES:"
  echo "  Node.js Backend          Standard TypeScript Node.js backend project with Jest testing"
  echo "  Frontend (Coming Soon)   TypeScript frontend project"
  echo "  Full-Stack (Coming Soon) Combined TypeScript frontend and backend project"
  echo ""
  echo "EXAMPLES:"
  echo "  # Create a project with interactive type selection"
  echo "  newTsp my-project"
  echo ""
  echo "  # Create a Node.js backend project directly"
  echo "  newTsp my-backend --node"
  echo ""
  echo "  # Create a project using TypeZero template"
  echo "  newTsp my-typezero-project --typezero"
  echo ""
  echo "NOTES:"
  echo "  - If no project type is specified, you will be prompted to select one."
  echo "  - The --typezero flag takes precedence over other project type options."
  echo "  - All projects are initialized with TypeScript, Jest, and standard configurations."
}
